// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IIncrementSystem {
  function increment() external returns (uint32);

  function spawn(int32 x, int32 y, int32 health) external;
}
